var myApp=angular.module('myApp',["ui.router","ctrls"]);
myApp.config(function($stateProvider,$urlRouterProvider){
    $urlRouterProvider.otherwise('/home');
    $stateProvider.state("home",{
        url:"/home",
        views:{
            "main":{
                templateUrl:'tpls/home.html'
            }
        }
    })
        .state("aboutUs",{
            url:"/aboutUs",
            views:{
                "main":{
                    templateUrl:'tpls/aboutUs.html',
                    controller:'aboutUsCtrl'
                }
            }
        })
        .state("news",{
            url:"/news",
            views:{
                "main":{
                    templateUrl:'tpls/news.html',
                    controller:'newsCtrl'
                }
            }
        })
        .state("newsListDetails",{
            url:"/newsDetails/:id/:newsTitle",
            views:{
                "main":{
                    templateUrl:"tpls/newsDetails.html",
                    "controller":"newsDetailCtrl"
                }
            }
        })
})